# Reference on this file: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Lint, build and test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Lint, build and test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Show the environment variables
        run: printenv
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: nodemodules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: nodemodules-
      - name: Install Node packages
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Build the Node.js tools
        run: yarn --cwd node build
      - name: Test the example project on BrowserStack
        run: "yarn --cwd example_project test:browserstack --log-level ${{ github.run_attempt == 1 && 'info' || 'debug' }}"
        env:
          BROWSERSTACK_USERNAME: ${{secrets.BROWSERSTACK_USERNAME}}
          BROWSERSTACK_ACCESS_KEY: ${{secrets.BROWSERSTACK_ACCESS_KEY}}

      # The following steps will be replaced with automatic publishing
      - name: Pack the Node.js tools
        run: yarn --cwd node pack
      - name: Save the packages
        uses: actions/upload-artifact@v3
        with:
          name: Packages
          path: node/*.tgz
          if-no-files-found: error
