# Reference on this file: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Lint, build and test
on: [push]

env:
  BROWSERSTACK_USERNAME: ${{secrets.BROWSERSTACK_USERNAME}}
  BROWSERSTACK_ACCESS_KEY: ${{secrets.BROWSERSTACK_ACCESS_KEY}}
jobs:
  build:
    name: Lint, build and test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        hello: ['one', 'two']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: nodemodules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: nodemodules-
      - name: 'BrowserStackLocal stop'
        uses: 'browserstack/github-actions/setup-local@master'
        with:
          local-testing: stop
        if: ${{ always() }}
      - name: Install Node packages
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Build the Node.js tools
        run: yarn --cwd node build
      - name: 'BrowserStackLocal Setup'
        uses: 'browserstack/github-actions/setup-local@master'
        with:
          local-testing: start
          local-identifier: ${{ matrix.hello }}
          local-args: --force-local --force
      - name: Test the example project on BrowserStack
        run: HELLO=${{ matrix.hello }} yarn --cwd example_project test:browserstack --log-level debug
      - name: 'BrowserStackLocal off'
        uses: 'browserstack/github-actions/setup-local@master'
        with:
          local-testing: stop
        if: ${{ always() }}
      # The following steps will be replaced with automatic publishing
      - name: Pack the Node.js tools
        run: yarn --cwd node pack
      - name: Save the packages
        uses: actions/upload-artifact@v3
        with:
          name: Packages
          path: node/*.tgz
          if-no-files-found: error
